name: "Send Slack-notifikasjon"
description: "Send en fint formatert Slack-notifikasjon med status for et GitHub Actions workflow-run"

inputs:
  status:
    description: "Status på jobben (hentes fra jobs.status)"
    required: true
  webhook_url:
    description: "Slack Webhook som varsel skal sendes til"
    required: true
  environment:
    description: "Miljø som action har blitt kjørt for"
    required: false

runs:
  using: "node20"
  main: "src/main.js"
