name: "Send Slack-notifikasjon"
description: "Send en fint formatert Slack-notifikasjon med status for et GitHub Actions workflow-run"

inputs:
  status:
    description: "Status på jobben (hentes fra jobs.status)"
    required: true
  webhook_url:
    description: "Slack Webhook som varsel skal sendes til"
    required: true

runs:
  using: "composite"
  steps:
    - uses: adamkdean/simple-slack-notify@v1.1.2
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
        RUN_URL: "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"
      with:
        status: ${{ inputs.status }}
        success_text: "[${env.GITHUB_REPOSITORY}] ${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) ferdig"
        failure_text: "[${env.GITHUB_REPOSITORY}] ${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) feilet"
        cancelled_text: "[${env.GITHUB_REPOSITORY}] ${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) ble avbrutt"
        fields: |
          [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true},
          {"title": "Branch", "value": "${env.BRANCH}", "short": true},
          {"title": "Lenke til run", "value": "${env.RUN_URL}", "short": true}]
