name: Test notifikasjon

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        if: always()
        uses: andrlriis/slack-notification-action@master
        with:
          status: ${{ job.status }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
